package com.javaweb.model;
// Generated Nov 21, 2016 8:56:42 PM by Hibernate Tools 4.3.1



/**
 * TbFeedback generated by hbm2java
 */
public class TbFeedback  implements java.io.Serializable {


     private Integer id;
     private String fullname;
     private String title;
     private String email;
     private String conntent;
     private String notes;

    public TbFeedback() {
    }

    public TbFeedback(String fullname, String title, String email, String conntent, String notes) {
       this.fullname = fullname;
       this.title = title;
       this.email = email;
       this.conntent = conntent;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getConntent() {
        return this.conntent;
    }
    
    public void setConntent(String conntent) {
        this.conntent = conntent;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


