package com.javaweb.model;
// Generated Nov 21, 2016 8:56:42 PM by Hibernate Tools 4.3.1



/**
 * TbFkProductCategory generated by hbm2java
 */
public class TbFkProductCategory  implements java.io.Serializable {


     private Integer id;
     private Integer productid;
     private Integer categoryid;
     private String description;

    public TbFkProductCategory() {
    }

    public TbFkProductCategory(Integer productid, Integer categoryid, String description) {
       this.productid = productid;
       this.categoryid = categoryid;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getProductid() {
        return this.productid;
    }
    
    public void setProductid(Integer productid) {
        this.productid = productid;
    }
    public Integer getCategoryid() {
        return this.categoryid;
    }
    
    public void setCategoryid(Integer categoryid) {
        this.categoryid = categoryid;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


