package com.javaweb.model;
// Generated Nov 21, 2016 4:09:01 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbNews generated by hbm2java
 */
public class TbNews  implements java.io.Serializable {


     private Integer id;
     private Integer author;
     private Date newsDate;
     private String title;
     private String content;
     private String excerpt;
     private String images;
     private Boolean isbest;
     private Boolean isshow;
     private int status;
     private Integer count;
     private String tags;

    public TbNews() {
    }

	
    public TbNews(String title, String content, String excerpt, int status) {
        this.title = title;
        this.content = content;
        this.excerpt = excerpt;
        this.status = status;
    }
    public TbNews(Integer author, Date newsDate, String title, String content, String excerpt, String images, Boolean isbest, Boolean isshow, int status, Integer count, String tags) {
       this.author = author;
       this.newsDate = newsDate;
       this.title = title;
       this.content = content;
       this.excerpt = excerpt;
       this.images = images;
       this.isbest = isbest;
       this.isshow = isshow;
       this.status = status;
       this.count = count;
       this.tags = tags;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getAuthor() {
        return this.author;
    }
    
    public void setAuthor(Integer author) {
        this.author = author;
    }
    public Date getNewsDate() {
        return this.newsDate;
    }
    
    public void setNewsDate(Date newsDate) {
        this.newsDate = newsDate;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getExcerpt() {
        return this.excerpt;
    }
    
    public void setExcerpt(String excerpt) {
        this.excerpt = excerpt;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }
    public Boolean getIsbest() {
        return this.isbest;
    }
    
    public void setIsbest(Boolean isbest) {
        this.isbest = isbest;
    }
    public Boolean getIsshow() {
        return this.isshow;
    }
    
    public void setIsshow(Boolean isshow) {
        this.isshow = isshow;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public Integer getCount() {
        return this.count;
    }
    
    public void setCount(Integer count) {
        this.count = count;
    }
    public String getTags() {
        return this.tags;
    }
    
    public void setTags(String tags) {
        this.tags = tags;
    }




}


