package com.javaweb.model;
// Generated Nov 21, 2016 8:56:42 PM by Hibernate Tools 4.3.1



/**
 * TbNewsCategory generated by hbm2java
 */
public class TbNewsCategory  implements java.io.Serializable {


     private Integer id;
     private String categoryname;
     private String img;
     private String description;

    public TbNewsCategory() {
    }

	
    public TbNewsCategory(String categoryname, String img) {
        this.categoryname = categoryname;
        this.img = img;
    }
    public TbNewsCategory(String categoryname, String img, String description) {
       this.categoryname = categoryname;
       this.img = img;
       this.description = description;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCategoryname() {
        return this.categoryname;
    }
    
    public void setCategoryname(String categoryname) {
        this.categoryname = categoryname;
    }
    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


