package com.javaweb.model;
// Generated Nov 17, 2016 10:54:11 PM by Hibernate Tools 4.3.1



/**
 * TbPages generated by hbm2java
 */
public class TbPages  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String description;
     private String content;
     private String link;
     private Boolean securitypage;
     private String note;

    public TbPages() {
    }

	
    public TbPages(String title, String description, String content, String link) {
        this.title = title;
        this.description = description;
        this.content = content;
        this.link = link;
    }
    public TbPages(String title, String description, String content, String link, Boolean securitypage, String note) {
       this.title = title;
       this.description = description;
       this.content = content;
       this.link = link;
       this.securitypage = securitypage;
       this.note = note;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Boolean getSecuritypage() {
        return this.securitypage;
    }
    
    public void setSecuritypage(Boolean securitypage) {
        this.securitypage = securitypage;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


