package com.javaweb.model;
// Generated Nov 21, 2016 8:56:42 PM by Hibernate Tools 4.3.1



/**
 * TbProductCategory generated by hbm2java
 */
public class TbProductCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String image;
     private String notes;

    public TbProductCategory() {
    }

    public TbProductCategory(String name, String description, String image, String notes) {
       this.name = name;
       this.description = description;
       this.image = image;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


