package com.javaweb.model;
// Generated Nov 21, 2016 8:56:42 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TbProduct generated by hbm2java
 */
public class TbProduct  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private String shortDes;
     private Long price;
     private Integer amout;
     private Date date;
     private Integer viewcount;
     private Boolean isbest;
     private Boolean isshow;
     private Long promotionprice;
     private String images;
     private String tags;
     private String notes;

    public TbProduct() {
    }

	
    public TbProduct(String name) {
        this.name = name;
    }
    public TbProduct(String name, String description, String shortDes, Long price, Integer amout, Date date, Integer viewcount, Boolean isbest, Boolean isshow, Long promotionprice, String images, String tags, String notes) {
       this.name = name;
       this.description = description;
       this.shortDes = shortDes;
       this.price = price;
       this.amout = amout;
       this.date = date;
       this.viewcount = viewcount;
       this.isbest = isbest;
       this.isshow = isshow;
       this.promotionprice = promotionprice;
       this.images = images;
       this.tags = tags;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getShortDes() {
        return this.shortDes;
    }
    
    public void setShortDes(String shortDes) {
        this.shortDes = shortDes;
    }
    public Long getPrice() {
        return this.price;
    }
    
    public void setPrice(Long price) {
        this.price = price;
    }
    public Integer getAmout() {
        return this.amout;
    }
    
    public void setAmout(Integer amout) {
        this.amout = amout;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getViewcount() {
        return this.viewcount;
    }
    
    public void setViewcount(Integer viewcount) {
        this.viewcount = viewcount;
    }
    public Boolean getIsbest() {
        return this.isbest;
    }
    
    public void setIsbest(Boolean isbest) {
        this.isbest = isbest;
    }
    public Boolean getIsshow() {
        return this.isshow;
    }
    
    public void setIsshow(Boolean isshow) {
        this.isshow = isshow;
    }
    public Long getPromotionprice() {
        return this.promotionprice;
    }
    
    public void setPromotionprice(Long promotionprice) {
        this.promotionprice = promotionprice;
    }
    public String getImages() {
        return this.images;
    }
    
    public void setImages(String images) {
        this.images = images;
    }
    public String getTags() {
        return this.tags;
    }
    
    public void setTags(String tags) {
        this.tags = tags;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


