package com.javaweb.model;
// Generated Nov 21, 2016 4:09:01 PM by Hibernate Tools 4.3.1



/**
 * TbRoles generated by hbm2java
 */
public class TbRoles  implements java.io.Serializable {


     private Integer idroles;
     private String rolename;
     private String description;

    public TbRoles() {
    }

	
    public TbRoles(String rolename) {
        this.rolename = rolename;
    }
    public TbRoles(String rolename, String description) {
       this.rolename = rolename;
       this.description = description;
    }
   
    public Integer getIdroles() {
        return this.idroles;
    }
    
    public void setIdroles(Integer idroles) {
        this.idroles = idroles;
    }
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


