package com.javaweb.model;
// Generated Nov 17, 2016 10:54:11 PM by Hibernate Tools 4.3.1



/**
 * TbUserRole generated by hbm2java
 */
public class TbUserRole  implements java.io.Serializable {


     private Integer iduserRole;
     private int userid;
     private int roleid;
     private String note;

    public TbUserRole() {
    }

	
    public TbUserRole(int userid, int roleid) {
        this.userid = userid;
        this.roleid = roleid;
    }
    public TbUserRole(int userid, int roleid, String note) {
       this.userid = userid;
       this.roleid = roleid;
       this.note = note;
    }
   
    public Integer getIduserRole() {
        return this.iduserRole;
    }
    
    public void setIduserRole(Integer iduserRole) {
        this.iduserRole = iduserRole;
    }
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }
    public int getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(int roleid) {
        this.roleid = roleid;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }




}


