package com.javaweb.model;
// Generated Nov 21, 2016 8:56:42 PM by Hibernate Tools 4.3.1



/**
 * TbWebinfo generated by hbm2java
 */
public class TbWebinfo  implements java.io.Serializable {


     private Integer id;
     private String title;
     private String description;
     private String logo;
     private String phone;
     private String address;
     private String email;
     private String notes;

    public TbWebinfo() {
    }

	
    public TbWebinfo(String title, String description) {
        this.title = title;
        this.description = description;
    }
    public TbWebinfo(String title, String description, String logo, String phone, String address, String email, String notes) {
       this.title = title;
       this.description = description;
       this.logo = logo;
       this.phone = phone;
       this.address = address;
       this.email = email;
       this.notes = notes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getLogo() {
        return this.logo;
    }
    
    public void setLogo(String logo) {
        this.logo = logo;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }




}


